[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    blynkkk/Blynk
    mathworks/ThingSpeak
    madhephaestus/ESP32Servo
    beegee-tokyo/DHT sensor library for ESPx
    arduino-libraries/LiquidCrystal